spring:
  profiles: default
  
datasource:
  master:
      driver-class-name: "com.mysql.jdbc.Driver"
      url: "jdbc:mysql://127.0.0.1:3306/surepark"
      user-name: "surepark"
      password: "surepark"
